apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global: null
    receivers:
    - name: default
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default
      repeat_interval: 3h
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          servity: 'warning'
        equal:
          - 'alertname'
    receivers:
      - name: 'default'
        webhook_configs:
          - send_resolved: false
            url: https://oapi.dingtalk.com/robot/send?access_token=7835a53a2db85968aae593a8578ea523e70079185231fb4e4182d613a34ffac3

